# Initial caps normalisation
echo <<< defining INITCAPS >>>
clear stack 

define initCap a (->) A, b (->) B, c (->) C, d (->) D, e (->) E, f (->) F,
g (->) G, h (->) H, i (->) I, j (->) J, k (->) K, l (->) L, m (->) M, n (->) N,
o (->) O, p (->) P, q (->) Q, r (->) R, s (->) S, t (->) T, u (->) U, v (->) V,
w (->) W, x (->) X, y (->) Y, z (->) Z,
á (->) Á, é (->) É, í (->) Í, ó (->) Ó, ú (->) Ú || .#. _ ;
push initCap

echo <<< SAVING initcaps.fst >>>

save stack bin/initcaps.fst

echo <<< COMPOSING >>>

!! NOW COMPOSED IN LOOKUP.SCRIPT
!!read regex initCap .o. @"int/fixed.fst";

read regex initCap .o. @"bin/all.fst";
save stack bin/initcaps-all.fst
