#!/usr/bin/perl

my %tags = (
    '+1P' => '<p1>', # First person
    '+2P' => '<p2>', # Second person
    '+3P' => '<p3>', # Third person
    '+Abr' => '<abbr>', # Abbreviation
    '+Adj' => '<adj>', # Adjective
    '+Adv' => '<adv>', # Adverb
    '+Art' => '<det><def>', # Article ('definite determiner'?)
    '+Auto' => '<impers>',  # Autonomous ('impersonal')
    '+Bar' => '<guio>', # hyphen, dash, etc.
    '+Base' => '<pst>', # Base form of adjective
    '+Brack' => '<lpar>,<rpar>', # Problem
    '+Card' => '<card>', # Cardinal number
    '+CC' => '<dialect><connacht>', # Connacht dialiect -
    '+ChildesID' => '<childesid>', # - 
    '+Cmc' => '<Cmc>', # Communicator
    '+CM' => '<dialect><mumhan>', # Munster dialect - 
    '+Cmpd' => '<Cmpd>', # Compound
    '+Cmpl' => '<cmpl>',
    '+CmpdNoGen' => '<CmpdNoGen>', 
    '+Com' => '<nom>', # Common case (nominative)
    '+Comp' => '<comp>', # Comparative adjectival form
    '+Cond' => '<Cond>', # Conditional mood
    '+Conj' => '<Conj>', # Conjunction
    '+Coord' => '<cnjcoo>', # Coordinate
    '+Cop' => '<cop>', # Copula
    '+Cp' => '<Cp>', 
    '+CU' => '<dialect><uladh>', # Ulster dialect -
    '+Cur' => '<Cur>',
    '+Dat' => '<dat>', # Dative case 
    '+DefArt' => '<DefArt>', # Definitive article?
    '+Def' => '<def>', # Def
    '+Deg' => '<Deg>', # Degree (e.g. Degree particle)
    '+Dem' => '<dem>', # Demonstrative
    '+DeNom' => '<n><stem>', 
    '+Dep' => '<Dep>', # Verbal dependent forms
    '+Det' => '<det>', # Determiner
    '+Dig' => '<Dig>',
    '+Dim' => '<Dim>', # Diminuitive
    '+Dir' => '<Dir>', # Directional prepositional phrase
    '+Direct' => '<Direct>', 
    '+Ecl' => '<Ecl>', # Eclipsis (Urú)
    '+Email' => '<Email>', 
    '+Emph' => '<emph>', # Emphatic pronoun
    '+End' => '<End>', # End bracket, quote, etc.
    '+English' => '<English>', # English
    '+Event' => '<Event>', # Laugh, sneeze, etc.
    '+Fem' => '<f>', # Feminine
    '+Filler' => '<Filler>', # Filler
    '+Fin' => '<Fin>', # Sentence final 
    '+Foreign' => '<Foreign>', # Foreign
    '+Fragment' => '<Fragment>', 
    '+FutInd' => '<FutInd>', # Future indicative
    '+Gen' => '<gen>', # Genitive case
    '+Gn' => '<gn>', # General adverb -
    '+GuessCmpd' => '<guess><cmpd>', # -
    '+Guess' => '<guess>', # -
    '+GuessPref' => '<guess><pref>', #-
    '+hPref' => '<hPref>', # h- prefix
    '+Idf' => '<ind>', # Indefinite noun
    '+Imper' => '<imp>', # Imperative mood
    '+Imp' => '<imperf>',
    '+Indirect' => '<indirect>', # -
    '+Inf' => '<inf>', # -
    '+Int' => '<int>', # Sentence-internal punctuation -
    '+Item' => '<item>',
    '+Itj' => '<ij>', # Interjection
    '+Its' => '<its>', # Intensifiers -
    '+Len' => '<len>', # Lenition -
    '+Loc' => '<loc>', # Locative prepositional phrase
    '+Masc' => '<m>', # Masculine 
    '+Neg' => '<neg>', # Negative 
    '+NegQ' => '<NegQ>',
    '+Nm' => '<num>', #-
    '+NotSlen' => '', # encode this by the absence of the <slender> tag
    '+Noun' => '<n>', # Noun
    '+NStem' => '<n><stem>', # denominal verbal noun -
    '+Num' => '<num>', # Numeral
    '+Obj' => '<obj>', #-
    '+Op' => '<op>', #-
    '+Ord' => '<ord>', # Ordinal number
    '+Part' => '<part>', # Particle
    '+PastImp' => '<past><imp>', # Past habitual -
    '+PastInd' => '<past><ind>', # Past indicative -
    '+Past' => '<past>', # Past
    '+PastSubj' => '<past><subj>', # Past subjunctive
    '+Pat' => '<pat>', # Pat
    '+PC' => '<pc>', #-
    '+Pers' => '<pers>', # Personal
    '+Pl' => '<pl>', # Plural
    '+Poss' => '<pos>', # Possessive
    '+Prep' => '<pr>', # Preposition
    '+PresImp' => '<pres><imp>', # Present imperative -
    '+PresInd' => '<pres><ind>', # Present indicative -
    '+Pres' => '<pres>', # Present
    '+PresSubj' => '<pres><subj>', # Present subjunctive -
    '+Pron' => '<prn>', # Pronoun 
    '+Prop' => '<np>', # Proper noun
    '+Pro' => '<pro>', # Pronoun with copula -
    '+Punct' => '<punct>', # Abbreviation -
    '+Q' => '<itg>', # Interrogative
    '+Qty' => '<qnt>', # Quantifier
    '+Quo' => '<lquot>,<rquot>', # quotes (Problem)
    '+Ref' => '<ref>', # Reflexive
    '+RelInd' => '<rel><ind>', # Relative indirect -
    '+Rel' => '<rel>', # Relative directm
    '+Sbj' => '<subj>', #- 
    '+Sg' => '<sg>', # Singular 
    '+Simp' => '<simp>', # Simple?
    '+Slender' => '<slender>', # Slender
    '+Strong' => '<strong>', # Strong plural
    '+St' => '<st>', # Begin quote, bracket, etc. (Problem)
    '+Subord' => '<cnjsub>', # Subordinate
    '+Subst' => '<Subst>', # substantive
    '+Temp' => '<Temp>', # Temporal adverb
    '+Title' => '<title>', # Mr, Mrs...
    '+VD' => '<v><dtv>', # Ditransitive verb
    '+Vb' => '<vb>', # Verbal particle
    '+Verbal' => '<verbal>', #-
    '+Verb' => '<v>', # Verb
    '+VF' => '<VF>', # Vowel form
    '+VI' => '<v><iv>', # Intransitive verb
    '+Voc' => '<voc>', # Vocative case
    '+Vow' => '<vow>', # Vowel-initial form -
    '+VTI' => '<v><tv>', # Transitive and intransitive verb
    '+VT' => '<v><tv>', # Transitive verb
    '+Weak' => '<weak>', # Weak adjective
    '+Xxx' => '<xxx>', # Unknown
);

my $filename = shift;

open SOURCE, $filename or die $!;

while (my $line = <SOURCE>) {
    while (($xfst_tag, $apertium_tag) = each %tags) {
        $xfst_tag =~ s/\+/\\+/g;
        $line =~ s/$xfst_tag/$apertium_tag/g;
    }
    print $line;
}
